name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DATABASE: "rbac"
          POSTGRES_USER: "rbac"
          POSTGRES_PASSWORD: "rbac-password"
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --tmpfs /var/lib/postgresql/data

    steps:
      - uses: actions/checkout@v4

      - name: Setup Roswell
        uses: macnod/roswell-action@v4
        with:
          sbcl-version: 2.5.10
          roswell-version: 23.10.14.114

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5434 -U cl-user -d rbac; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
          sleep 2

      - name: Initialize database
        env:
          PGPASSWORD: "rbac-password"
        run: |
          psql -h 127.0.0.1 -p 5434 -U rbac -d postgres \
            -f ${{ github.workspace }}/tests/db-init/init.sql

      - name: Install dependencies
        run: make install-dependencies

      - name: Compile
        run: make test-ci
        env:
          DB_HOST: "127.0.0.1"
          DB_PORT: "5434"
          DB_NAME: "rbac"
          DB_USER: "rbac"
          DB_PASSWORD: "rbac-password"
          RUN_TESTS: "false"
          RBAC_REPL: "false"

      - name: Run tests
        run: make test-ci
        env:
          DB_HOST: "127.0.0.1"
          DB_PORT: "5434"
          DB_NAME: "rbac"
          DB_USER: "rbac"
          DB_PASSWORD: "rbac-password"
          RUN_TESTS: "true"
          RBAC_REPL: "false"
